# Generated by Django 5.2.3 on 2025-06-30 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loginlog_options_logoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Failed Login Log',
                'verbose_name_plural': 'Başarısız Giriş Logları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
