# Generated by Django 5.2.3 on 2025-06-30 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_failedloginlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedloginlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Başarısız Giriş Logu', 'verbose_name_plural': 'Başarısız Giriş Logları'},
        ),
        migrations.AlterModelOptions(
            name='logoutlog',
            options={'ordering': ['-logout_time'], 'verbose_name': 'Logout Log', 'verbose_name_plural': 'Logout Logları'},
        ),
        migrations.RemoveField(
            model_name='logoutlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='logoutlog',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logoutlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logoutlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
